version: '3.1'

services:
  odoo:
    image: odoo:17
    container_name: odoo-test
    depends_on:
      - db
    ports:
      - "8050:8069"  # ⚠️ port différent de la prod
    volumes:
      - odoo-web-data-test:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    container_name: odoo-db-test
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data-test:/var/lib/postgresql/data

volumes:
  odoo-web-data-test:
  odoo-db-data-test:
