services:
  - type: web
    name: odoo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: odoo-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: odoo-db
          property: port

databases:
  - name: odoo-db
    plan: free
