services:
  - type: web
    name: odoo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: odoo-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: odoo-db
          property: port
    startCommand: >
      odoo --db_host=$HOST
           --db_port=$PGPORT
           --db_user=$USER
           --db_password=$PASSWORD
           --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
           --xmlrpc-port=10000
           --admin-passwd=pu1ss4nce7
